Generate accesstoken based on keyvault config
Altinn/altinn-accesstoken pull request #15
Opened 2023-03-23 11:15 UTC by acn-dgopa

Added extension method to generate access token by fetching certificate from keyvault

## Description

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2023-03-27 11:39 UTC, acn-dgopa commented
This involves keyvaukt integration and i'm bit confused on what kind of test will be sensible here. Any suggestions?

2023-03-28 09:47 UTC, TheTechArch approved these changes
Looks good

2023-03-28 10:15 UTC, SandGrainOne requested changes
Unnecessary config value?

2023-03-28 10:15 UTC, SandGrainOne commented on src/Altinn.Common.AccessTokenClient/Configuration/AccessTokenSettings.cs
> +        public int CacheCertLifetimeInSeconds { get; set; } = 3600;
I can't find where this is being used.

2023-03-28 10:32 UTC, SandGrainOne commented on src/Altinn.Common.AccessTokenClient/Services/ISigningCredentialsResolver.cs
> +        SigningCredentials GetSigningCredentialsFromKeyVault(string vaultUri, string secretId);
Adding methods to an interface implemented by other applications is a breaking change. Do we need this new method? 

AccessTokenClient provides one ISigningCredentialsResolver implementation in SigningCredentialsResolver. That implementation will currently try to find a certificate on the file system. Why not make a new implementation (e.g SigningCredentsialsKeyVaultResolver) that would try to find a certificate in a Key Vault instead of expanging the existing SigningCredentialsResolver? Will we ever need both in the same application?

The parameters could be given to the SigningCredentsialsKeyVaultResolver class through the constructor as a settings object.

2023-03-28 10:33 UTC, acn-dgopa commented on src/Altinn.Common.AccessTokenClient/Configuration/AccessTokenSettings.cs
> +        public int CacheCertLifetimeInSeconds { get; set; } = 3600;
removed

2023-03-28 10:33 UTC, SandGrainOne commented on src/Altinn.Common.AccessTokenClient/Services/SigningCredentialsResolver.cs
> +        private readonly IMemoryCache _memoryCache;
Doesn't look like _memoryCache is being used.

2024-01-25 09:32 UTC, SandGrainOne commented
The issues I pointed out in my review has not been resolved and the pull request is very old now. Assuming that the feature is unnecessary and that you found an other way to support the use of KeyVault.

The feature request is still registered, so we might return to this at a later time.

2024-01-25 09:32 UTC, closed without merging